# Default values for gpushare-installer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

masterCount: 3

kubeVersion: v1.14.2

schdInstallerImage: schd-extender-deployer:latest

evictDevicePluginImage: device-plugin-evict:latest

extenderImage: k8s-gpushare-schd-extender:latest

devicePluginImage: k8s-gpushare-plugin:latest

